enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
compression-level = 9


[YouTube]
enabled = false
build-mode = "both"
excluded-patches = ""
included-patches = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music]
enabled = false
build-mode = "both"
excluded-patches = ""
included-patches = ""
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[GooglePhotos]
enabled = false
build-mode = "both"
arch = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Music-Morphe]
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "apk"
version = "8.50.51"
excluded-patches = """\
    'Custom branding name for YouTube Music' \
    'Custom branding icon for YouTube Music' \
    """
included-patches = ""
arch = "arm64-v8a"
patches-version = "v1.2.0"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"


[YouTube-Morphe]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
version = "20.51.39"
excluded-patches = """\
    'Custom branding name for YouTube' \
    'Custom branding icon for YouTube' \
    """
arch = "arm64-v8a"
included-patches = ""
patches-version = "v1.2.0"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"



[Spotify]
enabled = false
app-name = "Spotify"
arch = "both"
patches-version = "dev"
included-patches = """\
    'Unlock Spotify Premium' \
    'Spoof signature' \
    'Custom theme' \
    """
patches-source = "anddea/revanced-patches"
cli-source = "revanced/revanced-cli"
rv-brand = "anddea"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"



[YouTube-Anddea]
enabled = false
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
rv-brand = "ReVanced Anddea"
cli-source = "inotia00/revanced-cli"
patches-version = "dev"
build-mode = "both"
excluded-patches = """\
    'Custom branding name for YouTube' \
    'Custom branding icon for YouTube' \
    """
included-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"


[Music-Anddea]
enabled = false
app-name = "Music"
patches-source = "anddea/revanced-patches"
rv-brand = "ReVanced Anddea"
cli-source = "inotia00/revanced-cli"
patches-version = "dev"
build-mode = "both"
excluded-patches = """\
    'Custom branding name for YouTube Music' \
    'Custom branding icon for YouTube Music' \
    """
included-patches = ""
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"


[Reddit-Extended]
enabled = false
app-name = "Reddit"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
version = "2026.01.0"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Twitter-X]
enabled = false
app-name = "X"
patches-source = "crimera/piko"
cli-source = "revanced/revanced-cli"
rv-brand = "Bizarre X"
build-mode = "both"
arch = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"


